[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
